### ISSUE TITLE
Implement leveling system

### ISSUE THREAD

**Issue by HeadTriXz** [HeadTriXz/Barry#13]
Create a system that tracks user activity and assigns experience and levels based on their participation in the server. Experience should be earned through various actions such as sending messages or participating in voice channels.

### To-do
- [ ] https://github.com/HeadTriXz/Barry/issues/10
- [ ] https://github.com/HeadTriXz/Barry/issues/11
- [ ] https://github.com/HeadTriXz/Barry/issues/12
