### ISSUE TITLE
Implement moderation features

### ISSUE THREAD

**Issue by HeadTriXz** [HeadTriXz/Barry#24]
Create a set of moderation tools to help moderators manage user behavior and enforce server rules. This includes features such as banning, kicking, muting, and warning.

Moderators should be able to view the history of cases, and delete specific cases if needed. Adding, editing, deleting, and viewing notes on a case should also be possible.

### To-do
- [x] https://github.com/HeadTriXz/Barry/issues/14
- [x] https://github.com/HeadTriXz/Barry/issues/15
- [x] https://github.com/HeadTriXz/Barry/issues/16
- [x] https://github.com/HeadTriXz/Barry/issues/17
- [x] https://github.com/HeadTriXz/Barry/issues/18
- [x] https://github.com/HeadTriXz/Barry/issues/19
- [x] https://github.com/HeadTriXz/Barry/issues/20
- [x] https://github.com/HeadTriXz/Barry/issues/21
- [x] https://github.com/HeadTriXz/Barry/issues/22
- [x] https://github.com/HeadTriXz/Barry/issues/23
