### ISSUE TITLE
Implement marketplace functionality

### ISSUE THREAD

**Issue by HeadTriXz** [HeadTriXz/Barry#32]
Create a marketplace system where users can create profiles and make requests.

### To-do Profiles
- [x] https://github.com/HeadTriXz/Barry/issues/25
- [x] https://github.com/HeadTriXz/Barry/issues/26
- [x] https://github.com/HeadTriXz/Barry/issues/27
- [ ] https://github.com/HeadTriXz/Barry/issues/28

### To-do Requests
- [x] https://github.com/HeadTriXz/Barry/issues/29
- [x] https://github.com/HeadTriXz/Barry/issues/30
- [ ] https://github.com/HeadTriXz/Barry/issues/31
