### ISSUE TITLE
Implement music playback functionality

### ISSUE THREAD

**Issue by HeadTriXz** [HeadTriXz/Barry#44]
### To-do
- [ ] https://github.com/HeadTriXz/Barry/issues/33
- [ ] https://github.com/HeadTriXz/Barry/issues/34
- [ ] https://github.com/HeadTriXz/Barry/issues/35
- [ ] https://github.com/HeadTriXz/Barry/issues/36
- [ ] https://github.com/HeadTriXz/Barry/issues/37
- [ ] https://github.com/HeadTriXz/Barry/issues/38
- [ ] https://github.com/HeadTriXz/Barry/issues/39
- [ ] https://github.com/HeadTriXz/Barry/issues/40
- [ ] https://github.com/HeadTriXz/Barry/issues/41
- [ ] https://github.com/HeadTriXz/Barry/issues/42
- [ ] https://github.com/HeadTriXz/Barry/issues/43
